### ISSUE TITLE
The process failed with exit code 1

### ISSUE THREAD

**Issue by prestonvanloon** [shogo82148/actions-go-fuzz#150]
Please see the following run: https://github.com/prysmaticlabs/prysm/actions/runs/5938462813/job/16102961363

```
Error: The process '/opt/hostedtoolcache/go/1.20.7/x64/bin/go' failed with exit code 1
```

Unfortunately, there are not many details on the failure. Any idea how we can resolve this?

**Comment by prestonvanloon** [comment]
I also tried to allow the list step to continue on error, but ran into [another issue](https://github.com/prysmaticlabs/prysm/actions/runs/5940089051).

```
Error when evaluating 'strategy' for job 'fuzz'. .github/workflows/fuzz.yml (Line: 33, Col: 18): Error parsing fromJson,.github/workflows/fuzz.yml (Line: 33, Col: 18): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/fuzz.yml (Line: 33, Col: 18): Unexpected value ''
```

**Comment by shogo82148** [comment]
Your test says "Tests in this package require extra build tag: re-run with `-tags develop`".

```
{"Time":"2023-08-22T12:04:17.602008795Z","Action":"output","Package":"github.com/prysmaticlabs/prysm/v4/beacon-chain/blockchain","Output":"time=\"2023-08-22T12:04:17Z\" level=fatal msg=\"Tests in this package require extra build tag: re-run with `-tags develop`\" prefix=blockchain\n"}
```

Unfortunately, there is currently no way to add the `-tags` option.

**Comment by shogo82148** [comment]
I've add a new `tags` input https://github.com/shogo82148/actions-go-fuzz/pull/154.
It makes the fuzzing test happy 😄  https://github.com/shogo82148/prysm/actions/runs/5958796156.

Here is a patch for your project: https://github.com/prysmaticlabs/prysm/pull/12790
